// Mock data for Islamic classical library

export const books = [
  {
    id: 1,
    title: "Al-Mabsut",
    arabicTitle: "المبسوط",
    author: "Imam al-Sarakhsi",
    authorArabic: "الإمام السرخسي",
    authorBirthYear: 400,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Comprehensive",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Classical",
    bookType: "Commentary",
    studyLevel: "Advanced",
    pages: 9000,
    publicationYear: "483 AH",
    scholarEra: "5th Century Hijri",
    description: "One of the most comprehensive and detailed works in Hanafi jurisprudence. Al-Sarakhsi dictated this monumental 30-volume work from memory while imprisoned, covering virtually every aspect of Islamic law.",
    uniqueAspects: "Unique for being dictated entirely from memory during imprisonment. Known for its extensive legal reasoning and detailed analysis of jurisprudential principles. Considered the encyclopedic reference for advanced Hanafi fiqh.",
    coverImage: "https://library.minaretandquill.com/book_covers/al-mabsut.jpg",
    isPlaceholder: false
  },
  {
    id: 2,
    title: "Badai' al-Sanai'",
    arabicTitle: "بدائع الصنائع",
    author: "Imam al-Kasani",
    authorArabic: "الإمام الكاساني",
    authorBirthYear: 500,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Systematic",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Classical",
    bookType: "Commentary",
    studyLevel: "Upper Intermediate",
    pages: 7000,
    publicationYear: "587 AH",
    scholarEra: "6th Century Hijri",
    description: "A systematic and well-organized exposition of Hanafi fiqh. Known for its clear methodology and logical presentation of legal opinions with their evidences.",
    uniqueAspects: "Stands out for its systematic organization and clarity. The author arranges topics logically and presents evidences with exceptional precision. Written as a commentary on his teacher's work, making complex issues accessible.",
    coverImage: "https://library.minaretandquill.com/book_covers/badai-al-sanai.jpg",
    isPlaceholder: false
  },
  {
    id: 3,
    title: "Al-Hidaya",
    arabicTitle: "الهداية",
    author: "Imam al-Marghinani",
    authorArabic: "الإمام المرغيناني",
    authorBirthYear: 511,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Intermediate Text",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Classical",
    bookType: "Matn",
    studyLevel: "Intermediate",
    pages: 2000,
    publicationYear: "593 AH",
    scholarEra: "6th Century Hijri",
    description: "The most widely taught intermediate text in Hanafi jurisprudence. It has been the primary textbook in Islamic seminaries for centuries and has numerous commentaries written on it.",
    uniqueAspects: "The gold standard for intermediate Hanafi studies. Its concise yet comprehensive coverage makes it ideal for students transitioning to advanced topics. Has over 100 commentaries written on it, showing its enduring importance.",
    coverImage: "https://library.minaretandquill.com/book_covers/al-hidaya.jpg",
    isPlaceholder: false,
    hasCommentaries: [{"id":11,"title":"Sharh Fath al-Qadir","author":"Ibn al-Humam"},{"id":4,"title":"Al-Ikhtiyar li Ta'lil al-Mukhtar","author":"Imam Abdullah ibn Mahmud al-Mawsili"}],
    publishedEditions: [
          {
                "publisher": "Dar al-Kotob al-Ilmiyah",
                "location": "Beirut, Lebanon",
                "year": "2000",
                "volumes": 4,
                "verified": true,
                "link": "https://www.sifatusafwa.com"
          },
          {
                "publisher": "Dar al-Arqam",
                "location": "Pakistan",
                "year": "2010",
                "volumes": 2,
                "verified": true,
                "link": null
          }
    ]
  },
  {
    id: 4,
    title: "Al-Ikhtiyar li Ta'lil al-Mukhtar",
    arabicTitle: "الاختيار لتعليل المختار",
    author: "Imam Abdullah ibn Mahmud al-Mawsili",
    authorArabic: "الإمام عبد الله بن محمود الموصلي",
    authorBirthYear: 599,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Evidences",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Classical",
    bookType: "Commentary",
    studyLevel: "Upper Intermediate",
    pages: 1800,
    publicationYear: "683 AH",
    scholarEra: "7th Century Hijri",
    description: "A valuable commentary explaining the evidences behind Hanafi rulings. Particularly useful for understanding the reasoning behind legal positions.",
    uniqueAspects: "Distinguished by its focus on explaining the 'why' behind rulings rather than just stating them. Provides scriptural evidences and rational arguments, making it essential for students who want to understand jurisprudential reasoning.",
    coverImage: "https://library.minaretandquill.com/book_covers/al-ikhtiyar-li-talil-al-mukhtar.jpg",
    isPlaceholder: false
  },
  {
    id: 5,
    title: "Kanz al-Daqa'iq",
    arabicTitle: "كنز الدقائق",
    author: "Imam al-Nasafi",
    authorArabic: "الإمام النسفي",
    authorBirthYear: 620,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Concise Text",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Classical",
    bookType: "Matn",
    studyLevel: "Intermediate",
    pages: 400,
    publicationYear: "710 AH",
    scholarEra: "8th Century Hijri",
    description: "A concise and precise compilation of Hanafi fiqh rulings. Despite its brevity, it covers essential topics with remarkable precision.",
    uniqueAspects: "Known for its extreme precision and economy of words. Every sentence is carefully crafted to convey maximum legal content. Popular in Ottoman and Indian seminaries. Its brevity makes it ideal for memorization.",
    coverImage: "https://library.minaretandquill.com/book_covers/kanz-al-daqaiq.jpg",
    isPlaceholder: false
  },
  {
    id: 6,
    title: "Nur al-Idah",
    arabicTitle: "نور الإيضاح",
    author: "Imam al-Shurunbulali",
    authorArabic: "الإمام الشرنبلالي",
    authorBirthYear: 994,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Ritual Worship",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Post-Classical",
    bookType: "Matn",
    studyLevel: "Beginner",
    pages: 150,
    publicationYear: "1069 AH",
    scholarEra: "11th Century Hijri",
    description: "A clear and accessible primer on ritual worship according to the Hanafi school. Widely used as a first text for beginning students.",
    uniqueAspects: "The most popular beginner text in Hanafi fiqh globally. Its clarity and focus on practical matters of worship make it perfect for new students. Covers prayer, fasting, zakat, and hajj in clear, simple language.",
    coverImage: "https://library.minaretandquill.com/book_covers/nur-al-idah.jpg",
    isPlaceholder: false
  },
  {
    id: 7,
    title: "Radd al-Muhtar 'ala al-Durr al-Mukhtar",
    arabicTitle: "رد المحتار على الدر المختار",
    author: "Ibn 'Abidin",
    authorArabic: "ابن عابدين",
    authorBirthYear: 1198,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Encyclopedia",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Modern",
    bookType: "Commentary",
    studyLevel: "Specialist",
    pages: 12000,
    publicationYear: "1252 AH",
    scholarEra: "13th Century Hijri",
    description: "The most authoritative reference work in Hanafi jurisprudence for fatwa. This multi-volume supercommentary is indispensable for muftis and advanced scholars.",
    uniqueAspects: "Considered the final word in Hanafi fiqh. Ibn 'Abidin's encyclopedic knowledge and ability to synthesize centuries of scholarship make this the go-to reference for complex legal questions. Essential for anyone issuing fatwas.",
    coverImage: "https://library.minaretandquill.com/book_covers/radd-al-muhtar-ala-al-durr-al-mukhtar.jpg",
    isPlaceholder: false
  },
  {
    id: 8,
    title: "Al-Fiqh al-Islami wa Adillatuhu",
    arabicTitle: "الفقه الإسلامي وأدلته",
    author: "Dr. Wahbah al-Zuhayli",
    authorArabic: "د. وهبة الزحيلي",
    authorBirthYear: 1351,
    category: "Fiqh",
    subject: "Comparative Jurisprudence - Contemporary",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Ash'ari",
    era: "Modern",
    bookType: "Commentary",
    studyLevel: "Upper Intermediate",
    pages: 11000,
    publicationYear: "1405 AH",
    scholarEra: "20th-21st Century",
    description: "A comprehensive modern encyclopedia of Islamic jurisprudence with detailed evidences. While comparative, it primarily follows the Hanafi school with extensive references to other madhabs.",
    uniqueAspects: "Bridges classical scholarship with contemporary issues. Unique for its detailed citation of evidences and comparison of all madhabs. Written in modern Arabic, making classical fiqh accessible to contemporary readers.",
    coverImage: "https://library.minaretandquill.com/book_covers/al-fiqh-al-islami-wa-adillatuhu.jpg",
    isPlaceholder: false
  },
  {
    id: 9,
    title: "Hashiyat Ibn 'Abidin al-Sughra",
    arabicTitle: "حاشية ابن عابدين الصغرى",
    author: "Ibn 'Abidin",
    authorArabic: "ابن عابدين",
    authorBirthYear: 1198,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Selected Topics",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Modern",
    bookType: "Commentary",
    studyLevel: "Advanced",
    pages: 3000,
    publicationYear: "1252 AH",
    scholarEra: "13th Century Hijri",
    description: "A shorter collection of Ibn 'Abidin's treatises on specific legal topics. Covers important contemporary issues that arose during his time.",
    uniqueAspects: "Contains Ibn 'Abidin's fatwas on novel issues of his era. Demonstrates how classical principles apply to new situations, making it valuable for understanding Islamic legal methodology.",
    coverImage: "https://library.minaretandquill.com/book_covers/hashiyat-ibn-abidin-al-sughra.jpg",
    isPlaceholder: false
  },
  {
    id: 10,
    title: "Mukhtasar al-Quduri",
    arabicTitle: "مختصر القدوري",
    author: "Imam al-Quduri",
    authorArabic: "الإمام القدوري",
    authorBirthYear: 362,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Foundational Text",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Classical",
    bookType: "Matn",
    studyLevel: "Beginner",
    pages: 300,
    publicationYear: "428 AH",
    scholarEra: "4th-5th Century Hijri",
    description: "The foundational primer in Hanafi jurisprudence. For centuries, this has been the first fiqh text studied by students in the Hanafi tradition.",
    uniqueAspects: "The starting point for Hanafi fiqh education. Its simple language and clear structure make it perfect for beginners. Despite its brevity, it covers all essential rulings. Al-Hidaya was actually written as a commentary on this text.",
    coverImage: "https://library.minaretandquill.com/book_covers/mukhtasar-al-quduri.jpg",
    isPlaceholder: false
  },
  {
    id: 11,
    title: "Sharh Fath al-Qadir",
    arabicTitle: "شرح فتح القدير",
    author: "Ibn al-Humam",
    authorArabic: "ابن الهمام",
    authorBirthYear: 790,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Advanced Commentary",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Post-Classical",
    bookType: "Commentary",
    studyLevel: "Advanced",
    pages: 8000,
    publicationYear: "861 AH",
    scholarEra: "9th Century Hijri",
    description: "An advanced commentary on al-Hidaya, combining fiqh with usul al-fiqh. Known for its depth and analytical rigor.",
    uniqueAspects: "Unique for integrating jurisprudential principles (usul) with applied law (furu'). Ibn al-Humam critically examines evidences and provides independent analysis, making this essential for scholars who want to understand the reasoning behind rulings.",
    coverImage: "https://library.minaretandquill.com/book_covers/sharh-fath-al-qadir.jpg",
    isPlaceholder: false,
    commentaryOf: "Al-Hidaya",
    hasCommentaries: [],
    publishedEditions: [
          {
                "publisher": "Dar al-Fikr",
                "location": "Beirut, Lebanon",
                "year": "1995",
                "volumes": 10,
                "verified": true,
                "link": null
          }
    ]
  },
  {
    id: 12,
    title: "Al-Fatawa al-Hindiyya",
    arabicTitle: "الفتاوى الهندية",
    author: "Multiple Scholars (Commissioned)",
    authorArabic: "مجموعة من العلماء",
    authorBirthYear: 1000,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Legal Encyclopedia",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Post-Classical",
    bookType: "Compilation",
    studyLevel: "Specialist",
    pages: 6000,
    publicationYear: "1092 AH",
    scholarEra: "11th Century Hijri",
    description: "A comprehensive compilation of Hanafi legal opinions commissioned by the Mughal emperor Aurangzeb. Compiled by a team of leading scholars.",
    uniqueAspects: "A unique collective work representing the consensus of Hanafi scholarship in the Indian subcontinent. Organized systematically for easy reference. Widely used for fatwa in South Asia and beyond.",
    coverImage: "https://library.minaretandquill.com/book_covers/al-fatawa-al-hindiyya.jpg",
    isPlaceholder: false
  },
  {
    id: 13,
    title: "Tabyīn al-Haqā'iq",
    arabicTitle: "تبيين الحقائق",
    author: "Imam al-Zayla'i",
    authorArabic: "الإمام الزيلعي",
    authorBirthYear: 620,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Commentary with Hadith",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Classical",
    bookType: "Commentary",
    studyLevel: "Advanced",
    pages: 4500,
    publicationYear: "743 AH",
    scholarEra: "8th Century Hijri",
    description: "A detailed commentary on Kanz al-Daqa'iq with extensive hadith references. Bridges the gap between Hanafi fiqh and its hadith foundations.",
    uniqueAspects: "Stands out for meticulously tracing Hanafi positions back to hadith sources. Essential for those who want to understand the hadith basis of Hanafi rulings. Contains valuable hadith analysis and authentication.",
    coverImage: "https://library.minaretandquill.com/book_covers/tabyin-al-haqaiq.jpg",
    isPlaceholder: false
  },
  {
    id: 14,
    title: "Majma' al-Anhur",
    arabicTitle: "مجمع الأنهر",
    author: "Shaykh Zada (Damad Afandi)",
    authorArabic: "شيخي زاده",
    authorBirthYear: 988,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Ottoman Standard",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Post-Classical",
    bookType: "Commentary",
    studyLevel: "Upper Intermediate",
    pages: 2500,
    publicationYear: "1078 AH",
    scholarEra: "11th Century Hijri",
    description: "A widely-used text in the Ottoman Empire, combining multiple earlier works. Known for its clarity and practical approach.",
    uniqueAspects: "Synthesizes multiple classical texts into one accessible work. Popular in Ottoman institutions for its balance between detail and readability. Includes both established positions and practical applications.",
    coverImage: "https://library.minaretandquill.com/book_covers/majma-al-anhur.jpg",
    isPlaceholder: false
  },
  {
    id: 15,
    title: "Fiqh al-Imam: Kitab al-Asl",
    arabicTitle: "كتاب الأصل",
    author: "Imam Muhammad al-Shaybani",
    authorArabic: "الإمام محمد الشيباني",
    authorBirthYear: 132,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Primary Source",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Athari",
    era: "Salaf",
    bookType: "Matn",
    studyLevel: "Advanced",
    pages: 5000,
    publicationYear: "189 AH",
    scholarEra: "2nd Century Hijri",
    description: "The foundational work of Hanafi jurisprudence by the direct student of Imam Abu Hanifa. Contains the earliest systematic exposition of Hanafi legal opinions.",
    uniqueAspects: "The primary source text for all later Hanafi works. Direct transmission from Imam Abu Hanifa's students. Essential for understanding the original Hanafi methodology and reasoning. All later Hanafi texts build on this foundation.",
    coverImage: "https://library.minaretandquill.com/book_covers/fiqh-al-imam-kitab-al-asl.jpg",
    isPlaceholder: false
  },
  {
    id: 16,
    title: "Sahih al-Bukhari",
    arabicTitle: "صحيح البخاري",
    author: "Imam al-Bukhari",
    authorArabic: "الإمام البخاري",
    authorBirthYear: 194,
    category: "Hadith",
    subject: "Prophetic Traditions - Most Authentic",
    madhab: "Independent",
    language: "Arabic",
    creed: "Athari",
    era: "Salaf",
    bookType: "Matn",
    studyLevel: "Intermediate",
    pages: 7563,
    publicationYear: "256 AH",
    scholarEra: "3rd Century Hijri",
    description: "The most authentic collection of Hadith in Islam. Imam Bukhari spent 16 years selecting these narrations from over 600,000 hadiths, applying the strictest criteria of authentication.",
    uniqueAspects: "Represents the pinnacle of hadith authentication methodology. Every hadith has an unbroken chain of reliable narrators. Organized by jurisprudential topics, making it both a hadith and fiqh reference. The foundation upon which Islamic law is built.",
    coverImage: "https://library.minaretandquill.com/book_covers/sahih-al-bukhari.jpg",
    isPlaceholder: false
  },
  {
    id: 17,
    title: "Sahih Muslim",
    arabicTitle: "صحيح مسلم",
    author: "Imam Muslim ibn al-Hajjaj",
    authorArabic: "الإمام مسلم بن الحجاج",
    authorBirthYear: 206,
    category: "Hadith",
    subject: "Prophetic Traditions - Authentic Collection",
    madhab: "Independent",
    language: "Arabic",
    creed: "Athari",
    era: "Salaf",
    bookType: "Matn",
    studyLevel: "Intermediate",
    pages: 7190,
    publicationYear: "261 AH",
    scholarEra: "3rd Century Hijri",
    description: "The second most authentic hadith collection, known for its superior organization and thematic arrangement. Imam Muslim presents hadiths on the same topic together with all their variations.",
    uniqueAspects: "Superior organization compared to Bukhari - groups all variants of a hadith together. More focused on authenticity than jurisprudential arrangement. Essential complement to Sahih Bukhari, together forming the 'Two Sahihs' (الصحيحان).",
    coverImage: "https://library.minaretandquill.com/book_covers/sahih-muslim.jpg",
    isPlaceholder: false
  },
  {
    id: 18,
    title: "Tafsir al-Qurtubi",
    arabicTitle: "الجامع لأحكام القرآن",
    author: "Imam al-Qurtubi",
    authorArabic: "الإمام القرطبي",
    authorBirthYear: 600,
    category: "Tafsir",
    subject: "Quranic Exegesis - Jurisprudential Focus",
    madhab: "Maliki",
    language: "Arabic",
    creed: "Ash'ari",
    era: "Classical",
    bookType: "Commentary",
    studyLevel: "Advanced",
    pages: 8000,
    publicationYear: "671 AH",
    scholarEra: "7th Century Hijri",
    description: "A comprehensive tafsir focused on extracting legal rulings from the Quran. Known as 'Al-Jami' li-Ahkam al-Quran' (The Compendium of Quranic Rulings), it presents various scholarly opinions on jurisprudential matters.",
    uniqueAspects: "Unique for its focus on fiqh rulings derived from verses. Presents opinions from all four madhabs. Combines linguistic analysis with legal extraction. Essential for understanding how jurists derive rulings from Quranic verses.",
    coverImage: "https://library.minaretandquill.com/book_covers/tafsir-al-qurtubi.jpg",
    isPlaceholder: false
  },
  {
    id: 19,
    title: "Al-Umm",
    arabicTitle: "الأم",
    author: "Imam al-Shafi'i",
    authorArabic: "الإمام الشافعي",
    authorBirthYear: 150,
    category: "Fiqh",
    subject: "Shafi'i Jurisprudence - Foundational Text",
    madhab: "Shafi'i",
    language: "Arabic",
    creed: "Athari",
    era: "Salaf",
    bookType: "Matn",
    studyLevel: "Advanced",
    pages: 4500,
    publicationYear: "204 AH",
    scholarEra: "2nd-3rd Century Hijri",
    description: "The primary jurisprudential work of Imam al-Shafi'i, the founder of one of the four Sunni schools of law. Contains his mature legal opinions and demonstrates his methodology in deriving rulings.",
    uniqueAspects: "Direct words of the founder of the Shafi'i madhab. Shows the practical application of usul al-fiqh principles. Contains Imam Shafi'i's new opinions (qaul jadid) formulated in Egypt. The foundation upon which the entire Shafi'i school is built.",
    coverImage: "https://library.minaretandquill.com/book_covers/al-umm.jpg",
    isPlaceholder: false
  },
  {
    id: 20,
    title: "Bidayat al-Mujtahid",
    arabicTitle: "بداية المجتهد ونهاية المقتصد",
    author: "Ibn Rushd al-Hafid (Averroes)",
    authorArabic: "ابن رشد الحفيد",
    authorBirthYear: 520,
    category: "Fiqh",
    subject: "Comparative Jurisprudence",
    madhab: "Maliki",
    language: "Arabic",
    creed: "Ash'ari",
    era: "Classical",
    bookType: "Commentary",
    studyLevel: "Advanced",
    pages: 2400,
    publicationYear: "595 AH",
    scholarEra: "6th Century Hijri",
    description: "A masterpiece of comparative Islamic jurisprudence. Ibn Rushd systematically presents different opinions on each legal issue, along with the evidences and reasoning behind each position.",
    uniqueAspects: "Unparalleled in comparative fiqh methodology. Presents all four madhabs' opinions with their evidences objectively. Shows the underlying principles behind legal differences. Essential for understanding ikhtilaf (jurisprudential disagreement) and training mujtahids.",
    coverImage: "https://library.minaretandquill.com/book_covers/bidayat-al-mujtahid.jpg",
    isPlaceholder: false
  },
  {
    id: 21,
    title: "Munyat al-Musalli",
    arabicTitle: "منية المصلي",
    author: "Imam Sadruddin al-Qunawi",
    authorArabic: "الإمام صدر الدين القونوي",
    authorBirthYear: 630,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Ritual Prayer",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Classical",
    bookType: "Matn",
    studyLevel: "Beginner",
    pages: 80,
    publicationYear: "710 AH",
    scholarEra: "7th-8th Century Hijri",
    description: "A concise primer on the rulings of prayer according to the Hanafi school. Covers essential matters every Muslim needs to know about salah.",
    uniqueAspects: "One of the most widely memorized texts on prayer in the Hanafi tradition. Its brevity and clarity make it ideal for beginners. Forms the foundation for understanding more detailed prayer rulings.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true
  },
  {
    id: 22,
    title: "Al-Fiqh al-Muyassar",
    arabicTitle: "الفقه الميسر",
    author: "Various Contemporary Scholars",
    authorArabic: "مجموعة من العلماء المعاصرين",
    authorBirthYear: 1350,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Simplified Contemporary",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Modern",
    bookType: "Reference",
    studyLevel: "Beginner",
    pages: 500,
    publicationYear: "1420 AH",
    scholarEra: "Contemporary",
    description: "A simplified modern presentation of Hanafi fiqh designed for contemporary students. Presents rulings in accessible language with modern examples.",
    uniqueAspects: "Bridges classical scholarship with modern life. Uses contemporary language while maintaining adherence to traditional Hanafi positions. Ideal for those new to Islamic jurisprudence.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true
  },
  {
    id: 23,
    title: "Sharh al-Wiqayah",
    arabicTitle: "شرح الوقاية",
    author: "Various Commentators",
    authorArabic: "عدة من الشُراح",
    authorBirthYear: 700,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Commentary",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Post-Classical",
    bookType: "Commentary",
    studyLevel: "Upper Intermediate",
    pages: 1500,
    publicationYear: "800 AH",
    scholarEra: "8th-9th Century Hijri",
    description: "A detailed commentary on al-Wiqayah, an important intermediate text in Hanafi jurisprudence. Explains legal reasoning and provides extensive analysis.",
    uniqueAspects: "Known for its systematic approach to explaining legal principles. Widely studied in South Asian madrasas. Bridges the gap between intermediate and advanced study.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true
  },
  {
    id: 24,
    title: "Birghivi's Fiqh of Menstruation",
    arabicTitle: "رسالة الحيض للبرغوي",
    author: "Imam Birgivi",
    authorArabic: "الإمام البرغوي",
    authorBirthYear: 929,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Women's Issues",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Post-Classical",
    bookType: "Epistle",
    studyLevel: "Intermediate",
    pages: 100,
    publicationYear: "981 AH",
    scholarEra: "10th Century Hijri",
    description: "A specialized treatise on the rulings related to menstruation, post-natal bleeding, and related matters. An essential reference for women's fiqh.",
    uniqueAspects: "One of the most detailed and practical guides on this important topic. Widely used by female scholars and students. Addresses common questions with clarity and precision.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true
  },
  {
    id: 25,
    title: "Fatawa Rizviyya",
    arabicTitle: "فتاوى رضوية",
    author: "Imam Ahmad Rida Khan",
    authorArabic: "الإمام أحمد رضا خان",
    authorBirthYear: 1272,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - South Asian Fatwas",
    madhab: "Hanafi",
    language: "Arabic/Urdu",
    creed: "Maturidi",
    era: "Modern",
    bookType: "Compilation",
    studyLevel: "Advanced",
    pages: 12000,
    publicationYear: "1340 AH",
    scholarEra: "13th-14th Century Hijri",
    description: "A massive 30-volume collection of legal verdicts covering contemporary issues faced by Muslims in the Indian subcontinent. Addresses modern challenges while adhering to classical Hanafi methodology.",
    uniqueAspects: "Unique for its comprehensive treatment of modern issues. Combines deep classical knowledge with practical application. Essential reference for South Asian Hanafi scholars dealing with contemporary questions.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true
  },
  {
    id: 26,
    title: "Bahar-e-Shari'at",
    arabicTitle: "بحر الشريعة",
    author: "Mufti Amjad Ali A'zami",
    authorArabic: "المفتي أمجد علي الأعظمي",
    authorBirthYear: 1296,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Comprehensive Urdu",
    madhab: "Hanafi",
    language: "Urdu",
    creed: "Maturidi",
    era: "Modern",
    bookType: "Commentary",
    studyLevel: "Intermediate",
    pages: 5000,
    publicationYear: "1375 AH",
    scholarEra: "14th Century Hijri",
    description: "A comprehensive Hanafi fiqh manual in Urdu covering all aspects of Islamic law. Written for the general Muslim public, combining accessibility with scholarly rigor.",
    uniqueAspects: "Most popular Hanafi fiqh book in Urdu. Presents complex rulings in simple language. Widely used by laypeople and students alike in South Asia. Includes practical examples from daily life.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true
  },
  {
    id: 27,
    title: "Maraqi al-Falah Sharh Nur al-Idah",
    arabicTitle: "مراقي الفلاح شرح نور الإيضاح",
    author: "Imam al-Shurunbulali",
    authorArabic: "الإمام الشرنبلالي",
    authorBirthYear: 994,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Ritual Worship Commentary",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Post-Classical",
    bookType: "Commentary",
    studyLevel: "Intermediate",
    pages: 400,
    publicationYear: "1069 AH",
    scholarEra: "11th Century Hijri",
    description: "The author's own commentary on his primer Nur al-Idah. Explains the rulings of worship with additional detail and evidences.",
    uniqueAspects: "Perfect combination of brevity and detail. The author explains his own matn, ensuring accuracy. Widely studied as the next step after Nur al-Idah. Essential for understanding worship acts.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true
  },
  {
    id: 28,
    title: "Maraqi al-Sa'adat",
    arabicTitle: "مراقي السعادات",
    author: "Abu al-Ikhlas al-Shurunbulali",
    authorArabic: "أبو الإخلاص الشرنبلالي",
    authorBirthYear: 1060,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Transactions",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Post-Classical",
    bookType: "Matn",
    studyLevel: "Intermediate",
    pages: 250,
    publicationYear: "1120 AH",
    scholarEra: "11th-12th Century Hijri",
    description: "A concise text on transactions and dealings according to the Hanafi school. Covers business, marriage, and other social contracts.",
    uniqueAspects: "Complements Nur al-Idah by focusing on mu'amalat (transactions) rather than 'ibadat (worship). Essential for understanding Islamic commercial law.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true
  },
  {
    id: 29,
    title: "Multaqa al-Abhur",
    arabicTitle: "ملتقى الأبحر",
    author: "Ibrahim al-Halabi",
    authorArabic: "إبراهيم الحلبي",
    authorBirthYear: 880,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Ottoman Legal Code",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Post-Classical",
    bookType: "Matn",
    studyLevel: "Upper Intermediate",
    pages: 600,
    publicationYear: "956 AH",
    scholarEra: "10th Century Hijri",
    description: "A comprehensive legal manual that became the basis for Ottoman legal codes. Synthesizes multiple earlier Hanafi works into one coherent text.",
    uniqueAspects: "Served as the foundation for Ottoman civil law (Mecelle). Combines opinions from various Hanafi authorities. Highly influential in shaping Islamic law application in the Ottoman Empire.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true
  },
  {
    id: 30,
    title: "Hashiyat al-Tahtawi 'ala Maraqi al-Falah",
    arabicTitle: "حاشية الطحطاوي على مراقي الفلاح",
    author: "Ahmad al-Tahtawi",
    authorArabic: "أحمد الطحطاوي",
    authorBirthYear: 1231,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Supercommentary",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Modern",
    bookType: "Commentary",
    studyLevel: "Advanced",
    pages: 800,
    publicationYear: "1231 AH",
    scholarEra: "13th Century Hijri",
    description: "An important gloss (hashiya) on Maraqi al-Falah, adding further explanation and contemporary relevance to the text.",
    uniqueAspects: "Bridges classical text with modern understanding. Addresses questions that arose after the original commentary. Essential for advanced students studying Maraqi al-Falah.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true
  },
  {
    id: 31,
    title: "Al-Durar al-Mubaha fi al-Hazr wa al-Ibaha",
    arabicTitle: "الدرر المباحة في الحظر والإباحة",
    author: "Muhammad al-Nahlawi",
    authorArabic: "محمد النحلاوي",
    authorBirthYear: 1255,
    category: "Usul al-Fiqh",
    subject: "Legal Maxims and Principles",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Modern",
    bookType: "Reference",
    studyLevel: "Advanced",
    pages: 400,
    publicationYear: "1338 AH",
    scholarEra: "13th-14th Century Hijri",
    description: "A work on legal maxims (qawa'id fiqhiyya) and their application in Hanafi jurisprudence. Explains the principles underlying legal rulings.",
    uniqueAspects: "Excellent introduction to legal theory. Shows how broad principles generate specific rulings. Essential for understanding the logic of Islamic law.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true
  },
  {
    id: 32,
    title: "Al-Lubab fi Sharh al-Kitab",
    arabicTitle: "اللباب في شرح الكتاب",
    author: "Imam al-Maydani",
    authorArabic: "الإمام الميداني",
    authorBirthYear: 530,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Commentary on Quduri",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Classical",
    bookType: "Commentary",
    studyLevel: "Upper Intermediate",
    pages: 800,
    publicationYear: "592 AH",
    scholarEra: "6th Century Hijri",
    description: "A scholarly commentary on Mukhtasar al-Quduri, explaining the reasoning behind the rulings with evidences and comparisons.",
    uniqueAspects: "One of the earliest and most respected commentaries on Quduri. Known for its balanced approach and clear explanations. Foundation for later commentaries.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true
  },
  {
    id: 33,
    title: "Tanwir al-Absar",
    arabicTitle: "تنوير الأبصار",
    author: "Muhammad al-Timurtashi",
    authorArabic: "محمد التمرتاشي",
    authorBirthYear: 960,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Comprehensive Matn",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Post-Classical",
    bookType: "Matn",
    studyLevel: "Upper Intermediate",
    pages: 400,
    publicationYear: "1004 AH",
    scholarEra: "10th-11th Century Hijri",
    description: "A comprehensive matn covering all chapters of Hanafi fiqh. Forms the base text for al-Durr al-Mukhtar and Radd al-Muhtar.",
    uniqueAspects: "The foundational matn upon which Ibn 'Abidin's famous works are built. Comprehensive yet concise. Essential for understanding advanced Hanafi scholarship.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true
  },
  {
    id: 34,
    title: "Majma' al-Bahrayn wa Multaqa al-Nahrayn",
    arabicTitle: "مجمع البحرين وملتقى النهرين",
    author: "Muzaffar al-Din ibn Sa'id al-Balkhi",
    authorArabic: "مظفر الدين بن سعيد البلخي",
    authorBirthYear: 640,
    category: "Fiqh",
    subject: "Comparative Hanafi Opinions",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Classical",
    bookType: "Reference",
    studyLevel: "Advanced",
    pages: 900,
    publicationYear: "740 AH",
    scholarEra: "7th-8th Century Hijri",
    description: "A work comparing different opinions within the Hanafi school, particularly focusing on variations between Iraqi and Transoxanian scholars.",
    uniqueAspects: "Unique for its focus on intra-madhab differences. Shows the diversity of opinion within Hanafi scholarship. Essential for understanding regional variations.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true
  },
  {
    id: 35,
    title: "Al-Wajiz fi Sharh al-Qawa'id al-Fiqhiyya",
    arabicTitle: "الوجيز في شرح القواعد الفقهية",
    author: "Dr. Abdul Karim Zaydan",
    authorArabic: "د. عبد الكريم زيدان",
    authorBirthYear: 1335,
    category: "Usul al-Fiqh",
    subject: "Legal Maxims",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Ash'ari",
    era: "Modern",
    bookType: "Commentary",
    studyLevel: "Advanced",
    pages: 500,
    publicationYear: "1410 AH",
    scholarEra: "Contemporary",
    description: "A modern explanation of the major legal maxims (qawa'id) in Islamic jurisprudence, with contemporary examples and applications.",
    uniqueAspects: "Makes classical legal theory accessible to modern readers. Uses contemporary examples to illustrate timeless principles. Essential for understanding how rulings are derived.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true
  },
  {
    id: 36,
    title: "Madkhal ila Madhhab Abi Hanifa",
    arabicTitle: "مدخل إلى مذهب أبي حنيفة",
    author: "Dr. Sa'id Ramadan al-Buti",
    authorArabic: "د. سعيد رمضان البوطي",
    authorBirthYear: 1347,
    category: "Fiqh",
    subject: "Introduction to Hanafi Madhab",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Ash'ari",
    era: "Modern",
    bookType: "Reference",
    studyLevel: "Intermediate",
    pages: 350,
    publicationYear: "1400 AH",
    scholarEra: "Contemporary",
    description: "A modern introduction to the Hanafi school of law, its methodology, development, and key features. Written by a renowned contemporary scholar.",
    uniqueAspects: "Perfect orientation to the Hanafi madhab for new students. Explains historical development and unique characteristics. Shows relevance of classical scholarship today.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true
  },
  {
    id: 37,
    title: "Ahsan al-Fatawa",
    arabicTitle: "أحسن الفتاوى",
    author: "Mufti Rashid Ahmad Ludhyanvi",
    authorArabic: "المفتي رشيد أحمد اللدهيانوي",
    authorBirthYear: 1343,
    category: "Fiqh",
    subject: "Contemporary Hanafi Fatwas",
    madhab: "Hanafi",
    language: "Urdu",
    creed: "Maturidi",
    era: "Modern",
    bookType: "Compilation",
    studyLevel: "Advanced",
    pages: 8000,
    publicationYear: "1430 AH",
    scholarEra: "Contemporary",
    description: "A comprehensive collection of contemporary fatwas addressing modern issues faced by Muslims. Combines classical principles with contemporary application.",
    uniqueAspects: "Addresses 20th and 21st century questions. Shows how classical Hanafi principles apply to modern life. Essential reference for contemporary issues.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true
  },
  {
    id: 38,
    title: "Sharh Ma'ani al-Athar",
    arabicTitle: "شرح معاني الآثار",
    author: "Imam al-Tahawi",
    authorArabic: "الإمام الطحاوي",
    authorBirthYear: 239,
    category: "Hadith",
    subject: "Hadith with Hanafi Fiqh Application",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Salaf",
    bookType: "Commentary",
    studyLevel: "Advanced",
    pages: 2500,
    publicationYear: "321 AH",
    scholarEra: "3rd-4th Century Hijri",
    description: "A comprehensive work explaining hadiths and their legal implications according to the Hanafi school. Shows how Hanafi positions are derived from hadith.",
    uniqueAspects: "Essential for understanding the hadith basis of Hanafi fiqh. Reconciles apparently contradictory narrations. Demonstrates Hanafi methodology in hadith interpretation.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true
  },
  {
    id: 39,
    title: "Fatawa Rahimiyya",
    arabicTitle: "فتاوى رحيمية",
    author: "Mufti Abdur Rahim Lajpuri",
    authorArabic: "المفتي عبد الرحيم اللاجبوري",
    authorBirthYear: 1303,
    category: "Fiqh",
    subject: "South Asian Contemporary Fatwas",
    madhab: "Hanafi",
    language: "Urdu/Arabic",
    creed: "Maturidi",
    era: "Modern",
    bookType: "Compilation",
    studyLevel: "Advanced",
    pages: 4000,
    publicationYear: "1380 AH",
    scholarEra: "14th Century Hijri",
    description: "A collection of legal verdicts addressing issues specific to the Indian subcontinent in the early 20th century.",
    uniqueAspects: "Valuable for understanding how classical Hanafi law was applied to colonial-era challenges. Addresses unique South Asian questions.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true
  },
  {
    id: 40,
    title: "Mukhtasar al-Wiqayah",
    arabicTitle: "مختصر الوقاية",
    author: "Mulla Ali al-Qari",
    authorArabic: "الملا علي القاري",
    authorBirthYear: 953,
    category: "Fiqh",
    subject: "Hanafi Jurisprudence - Abridged Text",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Post-Classical",
    bookType: "Matn",
    studyLevel: "Intermediate",
    pages: 300,
    publicationYear: "1014 AH",
    scholarEra: "10th-11th Century Hijri",
    description: "An abridgment of the famous al-Wiqayah text, making it more accessible for students while maintaining essential content.",
    uniqueAspects: "Condensed by a master scholar known for his expertise. Retains the essential rulings while removing redundancy. Popular in Ottoman and Mughal educational systems.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true
  },
  {
    id: 41,
    title: "Manzumah fi al-Khilafiyyat",
    arabicTitle: "منظومة في الخلافيات",
    author: "Imam al-Nasafi",
    authorArabic: "الإمام النسفي",
    authorBirthYear: 620,
    category: "Fiqh",
    subject: "Comparative Madhab Differences",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Classical",
    bookType: "Matn",
    studyLevel: "Advanced",
    pages: 200,
    publicationYear: "710 AH",
    scholarEra: "8th Century Hijri",
    description: "A poetic work outlining the major differences between the Hanafi school and other madhabs. Designed for memorization.",
    uniqueAspects: "Unique for being in verse form (nazm). Makes comparative fiqh easier to memorize. Shows respect for other madhabs while explaining Hanafi positions.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true
  },
  {
    id: 42,
    title: "Rasm al-Mufti",
    arabicTitle: "رسم المفتي",
    author: "Ibn 'Abidin",
    authorArabic: "ابن عابدين",
    authorBirthYear: 1198,
    category: "Usul al-Fiqh",
    subject: "Guidelines for Issuing Fatwas",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Modern",
    bookType: "Epistle",
    studyLevel: "Specialist",
    pages: 150,
    publicationYear: "1252 AH",
    scholarEra: "13th Century Hijri",
    description: "A treatise on the etiquette and methodology of issuing Islamic legal opinions (fatwas). Essential for anyone engaged in juristic reasoning.",
    uniqueAspects: "The authoritative guide on fatwa methodology in the Hanafi school. Outlines qualifications needed and procedures to follow. Essential for muftis.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true
  },
  {
    id: 43,
    title: "Hilyat al-Awliya wa Tabaqat al-Asfiya",
    arabicTitle: "حلية الأولياء وطبقات الأصفياء",
    author: "Abu Nu'aym al-Isfahani",
    authorArabic: "أبو نعيم الأصفهاني",
    authorBirthYear: 336,
    category: "Sufism & Spirituality",
    subject: "Inner Dimensions",
    madhab: "Shafi'i",
    language: "Arabic",
    creed: "Ash'ari",
    era: "Classical",
    bookType: "Compilation",
    studyLevel: "Upper Intermediate",
    pages: 5000,
    publicationYear: "430 AH",
    scholarEra: "10th-11th Century Hijri",
    description: "A multi-volume encyclopedic collection of lives, sayings, and reports about early pious figures, ascetics and proto-Sufi masters. Abu Nu'aym compiled hundreds of short biographies to defend and document the piety of early ascetics, distinguishing genuine pious practice from heterodox fringes.",
    uniqueAspects: "Its combination of hadith transmission apparatus and hagiographical narrative makes it a primary bridge between hadith scholarship and early Sufi literature. Abu Nu'aym composed it partly to rebut critics who painted all ascetics as heterodox. One of the foundational sources for the history of early Sufism and renunciation (zuhd).",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true,
    hasCommentaries: [],
    publishedEditions: [
          {
                "publisher": "Dar al-Kotob al-Ilmiyah",
                "location": "Beirut, Lebanon",
                "year": "2000",
                "volumes": 10,
                "verified": true,
                "link": null
          }
    ]
  },
  {
    id: 44,
    title: "Dala'il al-Nubuwwa",
    arabicTitle: "دلائل النبوة",
    author: "Abu Nu'aym al-Isfahani",
    authorArabic: "أبو نعيم الأصفهاني",
    authorBirthYear: 336,
    category: "Seerah",
    subject: "Prophetic Excellence",
    madhab: "Shafi'i",
    language: "Arabic",
    creed: "Ash'ari",
    era: "Classical",
    bookType: "Compilation",
    studyLevel: "Intermediate",
    pages: 800,
    publicationYear: "430 AH",
    scholarEra: "10th-11th Century Hijri",
    description: "A thematic compilation centering on the virtues and signs of Prophet Muhammad, useful for devotional reading and as a source base for later compilations on the Prophet's merits. It gathers narrations, Quranic proofs, and reports used in later devotional literature.",
    uniqueAspects: "One of the early compendia devoted solely to the Prophet's merits and signs. The work was later expanded and reworked by other scholars including al-Bayhaqi who produced a larger work on similar themes.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true,
    hasCommentaries: [],
    publishedEditions: []
  },
  {
    id: 45,
    title: "Dhikr Akhbar Isfahan",
    arabicTitle: "ذكر أخبار أصبهان",
    author: "Abu Nu'aym al-Isfahani",
    authorArabic: "أبو نعيم الأصفهاني",
    authorBirthYear: 336,
    category: "History",
    subject: "Islamic History",
    madhab: "Shafi'i",
    language: "Arabic",
    creed: "Ash'ari",
    era: "Classical",
    bookType: "Reference",
    studyLevel: "Intermediate",
    pages: 1200,
    publicationYear: "430 AH",
    scholarEra: "10th-11th Century Hijri",
    description: "A collection of historical notices, announcements and biographies related to the city and region of Isfahan. Serves as a local source for events and personalities, documenting the scholarly and cultural life of this important center of Islamic learning.",
    uniqueAspects: "One of the earliest comprehensive local histories of an Islamic city. Provides invaluable information about the scholarly networks and intellectual life of Isfahan during the classical period.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true,
    hasCommentaries: [],
    publishedEditions: []
  },
  {
    id: 46,
    title: "Kitab al-Du'afa'",
    arabicTitle: "كتاب الضعفاء",
    author: "Abu Nu'aym al-Isfahani",
    authorArabic: "أبو نعيم الأصفهاني",
    authorBirthYear: 336,
    category: "Hadith",
    subject: "Hadith Commentary",
    madhab: "Shafi'i",
    language: "Arabic",
    creed: "Ash'ari",
    era: "Classical",
    bookType: "Reference",
    studyLevel: "Advanced",
    pages: 600,
    publicationYear: "430 AH",
    scholarEra: "10th-11th Century Hijri",
    description: "A catalogue of weak transmitters and narrators; a tool for assessing hadith reliability. Used by hadith students and scholars who research narrator reliability.",
    uniqueAspects: "Essential reference for hadith criticism (ilm al-rijal). Provides critical assessments of narrators whose reliability was questioned, helping scholars evaluate the authenticity of hadith chains.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true,
    hasCommentaries: [],
    publishedEditions: []
  },
  {
    id: 47,
    title: "Fada'il al-Khulafa' al-Arba'a",
    arabicTitle: "فضائل الخلفاء الأربعة وغيرهم",
    author: "Abu Nu'aym al-Isfahani",
    authorArabic: "أبو نعيم الأصفهاني",
    authorBirthYear: 336,
    category: "History",
    subject: "Islamic History",
    madhab: "Shafi'i",
    language: "Arabic",
    creed: "Ash'ari",
    era: "Classical",
    bookType: "Compilation",
    studyLevel: "Intermediate",
    pages: 400,
    publicationYear: "430 AH",
    scholarEra: "10th-11th Century Hijri",
    description: "A compilation of reports and virtues about the first rightly-guided caliphs and other prominent companions. Used as a source for later works on the merits of the caliphs.",
    uniqueAspects: "Provides balanced treatment of all four rightly-guided caliphs, useful for understanding early Islamic history and the virtues literature genre (fada'il).",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true,
    hasCommentaries: [],
    publishedEditions: []
  },
  {
    id: 48,
    title: "Ma'rifat al-Sahaba wa Fada'ilihim",
    arabicTitle: "معرفة الصحابة وفضائلهم",
    author: "Abu Nu'aym al-Isfahani",
    authorArabic: "أبو نعيم الأصفهاني",
    authorBirthYear: 336,
    category: "Seerah",
    subject: "Prophetic Biography",
    madhab: "Shafi'i",
    language: "Arabic",
    creed: "Ash'ari",
    era: "Classical",
    bookType: "Reference",
    studyLevel: "Intermediate",
    pages: 2000,
    publicationYear: "430 AH",
    scholarEra: "10th-11th Century Hijri",
    description: "A work listing companions' biographies and virtues. Used by students of hadith and seerah. It served as a model for later compilers such as Ibn Abd al-Barr and Ibn al-Athir.",
    uniqueAspects: "One of the earliest comprehensive biographical dictionaries of the Prophet's companions. Became a foundational reference for later works on the Sahaba.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true,
    hasCommentaries: [],
    publishedEditions: []
  },
  {
    id: 49,
    title: "Musnad al-Imam Abi Hanifa",
    arabicTitle: "مسند الإمام أبي حنيفة",
    author: "Abu Nu'aym al-Isfahani (compiler)",
    authorArabic: "أبو نعيم الأصفهاني",
    authorBirthYear: 336,
    category: "Hadith",
    subject: "Hadith with Fiqh Application",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Ash'ari",
    era: "Classical",
    bookType: "Compilation",
    studyLevel: "Advanced",
    pages: 500,
    publicationYear: "430 AH",
    scholarEra: "10th-11th Century Hijri",
    description: "A transmission and compilation of hadith material associated with Imam Abu Hanifa's circle. Useful for comparative hadith study and understanding the hadith foundations of early Hanafi jurisprudence.",
    uniqueAspects: "Important for documenting the hadith narrations associated with Imam Abu Hanifa. Shows the hadith knowledge of the Hanafi school's founder, compiled by a Shafi'i scholar showing inter-madhhab respect.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true,
    hasCommentaries: [],
    publishedEditions: []
  },
  {
    id: 50,
    title: "Al-Mustakhraj ala al-Bukhari wa Muslim",
    arabicTitle: "المستخرج على البخاري ومسلم",
    author: "Abu Nu'aym al-Isfahani",
    authorArabic: "أبو نعيم الأصفهاني",
    authorBirthYear: 336,
    category: "Hadith",
    subject: "Hadith Commentary",
    madhab: "Shafi'i",
    language: "Arabic",
    creed: "Ash'ari",
    era: "Classical",
    bookType: "Commentary",
    studyLevel: "Specialist",
    pages: 3000,
    publicationYear: "430 AH",
    scholarEra: "10th-11th Century Hijri",
    description: "Works that collect narrations which Abu Nu'aym judged to meet the standards of Sahih al-Bukhari and Sahih Muslim but which are not in those canonical collections. Useful to hadith critics and historians of transmission.",
    uniqueAspects: "Provides alternative chains (isnads) for hadiths in the two Sahihs, demonstrating the breadth of authentic transmission. Essential for advanced hadith criticism and understanding transmission networks.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true,
    hasCommentaries: [],
    publishedEditions: []
  },
  {
    id: 51,
    title: "Al-Tibb al-Nabawi",
    arabicTitle: "الطب النبوي",
    author: "Abu Nu'aym al-Isfahani",
    authorArabic: "أبو نعيم الأصفهاني",
    authorBirthYear: 336,
    category: "Hadith",
    subject: "Ethics & Spirituality",
    madhab: "Shafi'i",
    language: "Arabic",
    creed: "Ash'ari",
    era: "Classical",
    bookType: "Compilation",
    studyLevel: "Beginner",
    pages: 300,
    publicationYear: "430 AH",
    scholarEra: "10th-11th Century Hijri",
    description: "A collection of prophetic medical reports and therapeutic advice derived from hadith and praxis. Later literature on prophetic medicine references earlier compilers including Abu Nu'aym.",
    uniqueAspects: "One of the early compilations on prophetic medicine, documenting therapeutic traditions attributed to the Prophet. Influenced later works in this genre.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true,
    hasCommentaries: [],
    publishedEditions: []
  },
  {
    id: 52,
    title: "Tabaqat al-Muhaddithun wa al-Ruwat",
    arabicTitle: "طبقات المحدثين والرواة",
    author: "Abu Nu'aym al-Isfahani",
    authorArabic: "أبو نعيم الأصفهاني",
    authorBirthYear: 336,
    category: "Hadith",
    subject: "Hadith Commentary",
    madhab: "Shafi'i",
    language: "Arabic",
    creed: "Ash'ari",
    era: "Classical",
    bookType: "Reference",
    studyLevel: "Advanced",
    pages: 1500,
    publicationYear: "430 AH",
    scholarEra: "10th-11th Century Hijri",
    description: "A generational work classifying hadith scholars and transmitters by generation. Useful to specialists reconstructing chains and networks of transmission.",
    uniqueAspects: "Important biographical reference for hadith scholars (rijal). Organizes narrators by generation (tabaqat), essential for understanding the chronology of hadith transmission.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true,
    hasCommentaries: [],
    publishedEditions: []
  },
  {
    id: 53,
    title: "Al-Mufradat fi Gharib al-Qur'an",
    arabicTitle: "المفردات في غريب القرآن",
    author: "Raghib al-Isfahani",
    authorArabic: "الراغب الأصفهاني",
    authorBirthYear: 450,
    category: "Arabic Language",
    subject: "Arabic Lexicon",
    madhab: "N/A",
    language: "Arabic",
    creed: "N/A",
    era: "Classical",
    bookType: "Reference",
    studyLevel: "Upper Intermediate",
    pages: 600,
    publicationYear: "502 AH",
    scholarEra: "11th Century Hijri",
    description: "A concise but influential lexicon that analyzes Quranic vocabulary by root and meaning. Raghib combines philological discussion with semantic and ethical observations; entries often include Quranic occurrences and moral or theological remarks.",
    uniqueAspects: "One of the most important single-author lexica focused specifically on Quranic diction. Essential for understanding rarer Quranic terms and for semantic readings of the text. Often cited as a standard reference for Quranic vocabulary.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true,
    hasCommentaries: [],
    publishedEditions: [
          {
                "publisher": "Dar al-Qalam",
                "location": "Damascus, Syria",
                "year": "2009",
                "volumes": 1,
                "verified": true,
                "link": null
          }
    ]
  },
  {
    id: 54,
    title: "Al-Dhari'ah ila Makarim al-Shari'ah",
    arabicTitle: "الذريعة إلى مكارم الشريعة",
    author: "Raghib al-Isfahani",
    authorArabic: "الراغب الأصفهاني",
    authorBirthYear: 450,
    category: "Sufism & Spirituality",
    subject: "Inner Dimensions",
    madhab: "N/A",
    language: "Arabic",
    creed: "N/A",
    era: "Classical",
    bookType: "Epistle",
    studyLevel: "Intermediate",
    pages: 400,
    publicationYear: "502 AH",
    scholarEra: "11th Century Hijri",
    description: "The work collects moral exhortations and ethical teachings with a view to demonstrating the moral aims of shari'ah. It places scriptural and prophetic material within a programme of moral formation.",
    uniqueAspects: "Ties personal ethics to revealed law, showing how shari'ah aims at moral excellence. Typical of normative adab literature that integrates legal and ethical dimensions.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true,
    hasCommentaries: [],
    publishedEditions: []
  },
  {
    id: 55,
    title: "Muhadarat al-Udaba' wa Muhawarat al-Shu'ara'",
    arabicTitle: "محاضرات الأدباء ومحاورات الشعراء والبلغاء",
    author: "Raghib al-Isfahani",
    authorArabic: "الراغب الأصفهاني",
    authorBirthYear: 450,
    category: "Arabic Language",
    subject: "Arabic Grammar",
    madhab: "N/A",
    language: "Arabic",
    creed: "N/A",
    era: "Classical",
    bookType: "Reference",
    studyLevel: "Intermediate",
    pages: 800,
    publicationYear: "502 AH",
    scholarEra: "11th Century Hijri",
    description: "This work assembles lectures and dialogues on literary topics, rhetoric and the art of eloquence. It shows Raghib's engagement with Arabic literary culture, and helps place his semantic and moral reflections within a broader rhetorical and stylistic context.",
    uniqueAspects: "Demonstrates the connection between Quranic semantics and broader Arabic literary culture. Shows how understanding eloquence aids in understanding the Quran's linguistic miracles.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true,
    hasCommentaries: [],
    publishedEditions: []
  },
  {
    id: 56,
    title: "Risalah fi Adab al-Ikhtilat bi-an-Nas",
    arabicTitle: "رسالة في أدب الإختلاط بالناس",
    author: "Raghib al-Isfahani",
    authorArabic: "الراغب الأصفهاني",
    authorBirthYear: 450,
    category: "Sufism & Spirituality",
    subject: "Inner Dimensions",
    madhab: "N/A",
    language: "Arabic",
    creed: "N/A",
    era: "Classical",
    bookType: "Epistle",
    studyLevel: "Beginner",
    pages: 80,
    publicationYear: "502 AH",
    scholarEra: "11th Century Hijri",
    description: "This short treatise offers practical guidance on social conduct and etiquette. It typifies the classical Islamic concern with appropriate social behaviour, instructing readers on how to behave in mixed company, emphasizing decorum grounded in religious and cultural norms.",
    uniqueAspects: "Practical guide to Islamic social ethics. Shows how religious principles translate into everyday social interactions and proper conduct.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true,
    hasCommentaries: [],
    publishedEditions: []
  },
  {
    id: 57,
    title: "Tafsil al-Nash'atayn wa al-Tahsil al-Sa'adatayn",
    arabicTitle: "تفصيل النشأتين وتحصيل السعادتين",
    author: "Raghib al-Isfahani",
    authorArabic: "الراغب الأصفهاني",
    authorBirthYear: 450,
    category: "Sufism & Spirituality",
    subject: "Spiritual Purification",
    madhab: "N/A",
    language: "Arabic",
    creed: "N/A",
    era: "Classical",
    bookType: "Epistle",
    studyLevel: "Intermediate",
    pages: 350,
    publicationYear: "502 AH",
    scholarEra: "11th Century Hijri",
    description: "A systematic treatment of two modes of spiritual and life development and the attainment of blessedness. The work connects moral practice to ultimate felicity, showing the path to happiness in this world and the next.",
    uniqueAspects: "Integrates philosophical reflection on human nature with Islamic spiritual guidance. Shows the relationship between worldly and otherworldly success through moral cultivation.",
    coverImage: "https://library.minaretandquill.com/book_covers/pendingfrontcover.jpg",
    isPlaceholder: true,
    hasCommentaries: [],
    publishedEditions: []
  }
];

export const categories = [
  "All",
  "Tafsir",
  "Hadith",
  "Fiqh",
  "Aqeedah",
  "Seerah",
  "Arabic Language",
  "Usul al-Fiqh",
  "History",
  "Sufism & Spirituality"
];

export const authors = [
  "All",
  "Imam al-Sarakhsi",
  "Imam al-Kasani",
  "Imam al-Marghinani",
  "Imam Abdullah ibn Mahmud al-Mawsili",
  "Imam al-Nasafi",
  "Imam al-Shurunbulali",
  "Ibn 'Abidin",
  "Dr. Wahbah al-Zuhayli",
  "Imam al-Quduri",
  "Ibn al-Humam",
  "Multiple Scholars (Commissioned)",
  "Imam al-Zayla'i",
  "Shaykh Zada (Damad Afandi)",
  "Imam Muhammad al-Shaybani",
  "Imam al-Bukhari",
  "Imam Muslim ibn al-Hajjaj",
  "Imam al-Qurtubi",
  "Imam al-Shafi'i",
  "Ibn Rushd al-Hafid (Averroes)"
];

// Subjects organized by category
export const subjectsByCategory = {
  "Fiqh": [
    "All",
    "Comprehensive",
    "Systematic",
    "Intermediate Text",
    "Evidences",
    "Concise Text",
    "Ritual Worship",
    "Encyclopedia",
    "Selected Topics",
    "Foundational Text",
    "Advanced Commentary",
    "Legal Encyclopedia",
    "Commentary with Hadith",
    "Ottoman Standard",
    "Primary Source",
    "Comparative Jurisprudence",
    "Transactions",
    "Women's Issues",
    "Contemporary Issues"
  ],
  "Hadith": [
    "All",
    "Most Authentic",
    "Authentic Collection",
    "Hadith Commentary",
    "Ethics & Spirituality",
    "Hadith with Fiqh Application"
  ],
  "Tafsir": [
    "All",
    "Comprehensive Exegesis",
    "Hadith-based Exegesis",
    "Jurisprudential Focus"
  ],
  "Usul al-Fiqh": [
    "All",
    "Principles of Jurisprudence",
    "Legal Maxims",
    "Guidelines for Issuing Fatwas"
  ],
  "Aqeedah": [
    "All",
    "Islamic Creed",
    "Theological Principles"
  ],
  "Seerah": [
    "All",
    "Prophetic Biography",
    "Prophetic Guidance",
    "Prophetic Excellence"
  ],
  "History": [
    "All",
    "Islamic History",
    "Biographical Works"
  ],
  "Arabic Language": [
    "All",
    "Arabic Grammar",
    "Arabic Lexicon",
    "Morphology"
  ],
  "Sufism & Spirituality": [
    "All",
    "Inner Dimensions",
    "Spiritual Purification"
  ]
};

// Legacy flat list for backwards compatibility
export const subjects = [
  "All",
  "Hanafi Jurisprudence - Comprehensive",
  "Hanafi Jurisprudence - Systematic",
  "Hanafi Jurisprudence - Intermediate Text",
  "Hanafi Jurisprudence - Evidences",
  "Hanafi Jurisprudence - Concise Text",
  "Hanafi Jurisprudence - Ritual Worship",
  "Hanafi Jurisprudence - Encyclopedia",
  "Hanafi Jurisprudence - Selected Topics",
  "Hanafi Jurisprudence - Foundational Text",
  "Hanafi Jurisprudence - Advanced Commentary",
  "Hanafi Jurisprudence - Legal Encyclopedia",
  "Hanafi Jurisprudence - Commentary with Hadith",
  "Hanafi Jurisprudence - Ottoman Standard",
  "Hanafi Jurisprudence - Primary Source",
  "Comparative Jurisprudence - Contemporary",
  "Prophetic Traditions - Most Authentic",
  "Prophetic Traditions - Authentic Collection",
  "Quranic Exegesis - Jurisprudential Focus",
  "Shafi'i Jurisprudence - Foundational Text",
  "Comparative Jurisprudence"
];

// Commentary base texts for filtering
export const commentaryOfOptions = [
  "All",
  "Mukhtasar al-Quduri",
  "Al-Hidaya",
  "Kanz al-Daqa'iq",
  "Nur al-Idah",
  "Maraqi al-Falah",
  "Al-Wiqayah",
  "Tanwir al-Absar"
];

export const madhabs = [
  "All",
  "Hanafi",
  "Maliki",
  "Shafi'i",
  "Hanbali",
  "Comparative",
  "Independent",
  "N/A"
];

export const languages = [
  "All",
  "Arabic",
  "English",
  "Urdu",
  "Turkish",
  "Persian",
  "Malay"
];

export const creeds = [
  "All",
  "Athari",
  "Ash'ari",
  "Maturidi",
  "N/A"
];

export const eras = [
  "All",
  "Salaf",
  "Khalaf",
  "Classical",
  "Post-Classical",
  "Modern"
];

export const bookTypes = [
  "All",
  "Matn",
  "Commentary",
  "Translation",
  "Epistle",
  "Compilation",
  "Reference"
];

export const studyLevels = [
  "All",
  "Beginner",
  "Intermediate",
  "Upper Intermediate",
  "Advanced",
  "Specialist"
];

export const sortOptions = [
  { value: 'scholarBirthYear', label: 'Scholar Birth Year (Default)' },
  { value: 'publicationYear', label: 'Publication Year' },
  { value: 'title', label: 'Title (A-Z)' },
  { value: 'author', label: 'Author Name' },
  { value: 'studyLevel', label: 'Study Level' },
  { value: 'pages', label: 'Number of Pages' }
];