// Mock data for Islamic classical library

export const books = [
  {
    id: 1,
    title: "Tafsir al-Tabari",
    arabicTitle: "تفسير الطبري",
    author: "Imam al-Tabari",
    authorArabic: "الإمام الطبري",
    category: "Tafsir",
    subject: "Quranic Exegesis - Comprehensive",
    madhab: "Shafi'i",
    language: "Arabic",
    creed: "Athari",
    era: "Salaf",
    bookType: "Commentary",
    pages: 7200,
    publicationYear: "310 AH",
    scholarEra: "3rd Century Hijri",
    description: "One of the most comprehensive and authoritative commentaries on the Quran, known as Jami' al-Bayan 'an Ta'wil Ay al-Qur'an. This monumental work compiles interpretations from the Prophet's companions and early scholars.",
    coverImage: "https://images.unsplash.com/photo-1720701575003-51dafcf39cb4"
  },
  {
    id: 2,
    title: "Sahih al-Bukhari",
    arabicTitle: "صحيح البخاري",
    author: "Imam Bukhari",
    authorArabic: "الإمام البخاري",
    category: "Hadith",
    subject: "Prophetic Traditions - Sahih",
    madhab: "Independent",
    language: "Arabic",
    creed: "Athari",
    era: "Salaf",
    bookType: "Matn",
    pages: 3200,
    publicationYear: "256 AH",
    scholarEra: "3rd Century Hijri",
    description: "The most authentic collection of Hadith in Islam, compiled by Imam Muhammad ibn Ismail al-Bukhari. Contains approximately 7,563 hadiths with repetitions, selected from over 600,000 traditions.",
    coverImage: "https://images.pexels.com/photos/8164568/pexels-photo-8164568.jpeg"
  },
  {
    id: 3,
    title: "Sahih Muslim",
    arabicTitle: "صحيح مسلم",
    author: "Imam Muslim",
    authorArabic: "الإمام مسلم",
    category: "Hadith",
    subject: "Prophetic Traditions - Sahih",
    madhab: "Independent",
    language: "Arabic",
    creed: "Athari",
    era: "Salaf",
    bookType: "Matn",
    pages: 2800,
    publicationYear: "261 AH",
    scholarEra: "3rd Century Hijri",
    description: "The second most authentic hadith collection after Sahih al-Bukhari. Compiled by Imam Muslim ibn al-Hajjaj, it contains approximately 12,000 hadiths organized thematically.",
    coverImage: "https://images.pexels.com/photos/7429322/pexels-photo-7429322.jpeg"
  },
  {
    id: 4,
    title: "Al-Muwatta",
    arabicTitle: "الموطأ",
    author: "Imam Malik",
    authorArabic: "الإمام مالك",
    category: "Hadith",
    subject: "Prophetic Traditions & Fiqh",
    madhab: "Maliki",
    language: "Arabic",
    creed: "Athari",
    era: "Salaf",
    bookType: "Matn",
    pages: 1200,
    publicationYear: "179 AH",
    scholarEra: "2nd Century Hijri",
    description: "The earliest collection of hadith compiled by Imam Malik ibn Anas. It combines hadith with the legal opinions of the Medinan scholars and forms the foundation of Maliki jurisprudence.",
    coverImage: "https://images.pexels.com/photos/7249193/pexels-photo-7249193.jpeg"
  },
  {
    id: 5,
    title: "Al-Risala",
    arabicTitle: "الرسالة",
    author: "Imam al-Shafi'i",
    authorArabic: "الإمام الشافعي",
    category: "Usul al-Fiqh",
    subject: "Principles of Jurisprudence",
    madhab: "Shafi'i",
    language: "Arabic",
    creed: "Athari",
    era: "Salaf",
    bookType: "Epistle",
    pages: 450,
    publicationYear: "204 AH",
    scholarEra: "2nd-3rd Century Hijri",
    description: "The foundational text on Islamic legal theory (Usul al-Fiqh) by Imam Muhammad ibn Idris al-Shafi'i. It established the framework for deriving Islamic rulings from primary sources.",
    coverImage: "https://images.unsplash.com/photo-1696513553729-17129c427356"
  },
  {
    id: 6,
    title: "Bidayat al-Mujtahid",
    arabicTitle: "بداية المجتهد",
    author: "Ibn Rushd (Averroes)",
    authorArabic: "ابن رشد",
    category: "Fiqh",
    subject: "Comparative Jurisprudence",
    madhab: "Maliki",
    language: "Arabic",
    creed: "Ash'ari",
    era: "Classical",
    bookType: "Commentary",
    pages: 1800,
    publicationYear: "595 AH",
    scholarEra: "6th Century Hijri",
    description: "A comprehensive comparative fiqh manual by the great Andalusian scholar Ibn Rushd. It presents different scholarly opinions on various legal issues with their evidences.",
    coverImage: "https://images.unsplash.com/photo-1720701574998-d68020bce2bd"
  },
  {
    id: 7,
    title: "Al-Mughni",
    arabicTitle: "المغني",
    author: "Ibn Qudamah",
    authorArabic: "ابن قدامة",
    category: "Fiqh",
    subject: "Hanbali Jurisprudence",
    madhab: "Hanbali",
    language: "Arabic",
    creed: "Athari",
    era: "Classical",
    bookType: "Commentary",
    pages: 9000,
    publicationYear: "620 AH",
    scholarEra: "7th Century Hijri",
    description: "A monumental encyclopedia of Hanbali jurisprudence by Imam Muwaffaq al-Din Ibn Qudamah. It covers all aspects of Islamic law with detailed discussions and evidences.",
    coverImage: "https://images.unsplash.com/photo-1711350987526-06d69fdfbf64"
  },
  {
    id: 8,
    title: "Ihya Ulum al-Din",
    arabicTitle: "إحياء علوم الدين",
    author: "Imam al-Ghazali",
    authorArabic: "الإمام الغزالي",
    category: "Sufism & Spirituality",
    subject: "Islamic Sciences & Inner Dimensions",
    madhab: "Shafi'i",
    language: "Arabic",
    creed: "Ash'ari",
    era: "Classical",
    bookType: "Commentary",
    pages: 4000,
    publicationYear: "505 AH",
    scholarEra: "5th-6th Century Hijri",
    description: "The Revival of Religious Sciences - a masterpiece by Imam Abu Hamid al-Ghazali. This comprehensive work covers Islamic theology, jurisprudence, and spirituality, emphasizing inner dimensions of faith.",
    coverImage: "https://images.unsplash.com/photo-1734127317364-c0366298e048"
  },
  {
    id: 9,
    title: "Tafsir Ibn Kathir",
    arabicTitle: "تفسير ابن كثير",
    author: "Ibn Kathir",
    authorArabic: "ابن كثير",
    category: "Tafsir",
    subject: "Quranic Exegesis - Hadith-based",
    madhab: "Shafi'i",
    language: "Arabic",
    creed: "Athari",
    era: "Post-Classical",
    bookType: "Commentary",
    pages: 4800,
    publicationYear: "774 AH",
    scholarEra: "8th Century Hijri",
    description: "One of the most widely used Quranic commentaries. Ibn Kathir's tafsir explains the Quran through hadith and statements of the companions, making it highly reliable and accessible.",
    coverImage: "https://images.unsplash.com/photo-1710432102022-6742abc18621"
  },
  {
    id: 10,
    title: "Al-Sira al-Nabawiyya",
    arabicTitle: "السيرة النبوية",
    author: "Ibn Hisham",
    authorArabic: "ابن هشام",
    category: "Seerah",
    subject: "Prophetic Biography",
    madhab: "Independent",
    language: "Arabic",
    creed: "Athari",
    era: "Salaf",
    bookType: "Matn",
    pages: 1500,
    publicationYear: "218 AH",
    scholarEra: "3rd Century Hijri",
    description: "The definitive biography of Prophet Muhammad (peace be upon him), edited and refined by Ibn Hisham from Ibn Ishaq's original work. A primary source for the Prophet's life.",
    coverImage: "https://images.unsplash.com/photo-1701344176376-b0157fe85beb"
  },
  {
    id: 11,
    title: "Riyadh al-Salihin",
    arabicTitle: "رياض الصالحين",
    author: "Imam al-Nawawi",
    authorArabic: "الإمام النووي",
    category: "Hadith",
    subject: "Ethics & Spirituality",
    madhab: "Shafi'i",
    language: "Arabic",
    creed: "Ash'ari",
    era: "Classical",
    bookType: "Compilation",
    pages: 800,
    publicationYear: "676 AH",
    scholarEra: "7th Century Hijri",
    description: "The Gardens of the Righteous - a collection of authentic hadiths organized by topic, covering Islamic ethics, manners, and spirituality. One of the most beloved hadith compilations.",
    coverImage: "https://images.unsplash.com/photo-1670852738736-c9e4a6889012"
  },
  {
    id: 12,
    title: "Al-Aqidah al-Tahawiyyah",
    arabicTitle: "العقيدة الطحاوية",
    author: "Imam al-Tahawi",
    authorArabic: "الإمام الطحاوي",
    category: "Aqeedah",
    subject: "Islamic Creed",
    madhab: "Hanafi",
    language: "Arabic",
    creed: "Maturidi",
    era: "Salaf",
    bookType: "Matn",
    pages: 150,
    publicationYear: "321 AH",
    scholarEra: "4th Century Hijri",
    description: "A concise statement of Sunni Islamic doctrine by Imam Abu Ja'far al-Tahawi. This text has been widely accepted as an authoritative articulation of Islamic belief.",
    coverImage: "https://images.pexels.com/photos/34548784/pexels-photo-34548784.jpeg"
  },
  {
    id: 13,
    title: "Kitab Sibyawayh",
    arabicTitle: "كتاب سيبويه",
    author: "Sibyawayh",
    authorArabic: "سيبويه",
    category: "Arabic Language",
    subject: "Arabic Grammar",
    madhab: "N/A",
    language: "Arabic",
    creed: "N/A",
    era: "Salaf",
    bookType: "Matn",
    pages: 1200,
    publicationYear: "180 AH",
    scholarEra: "2nd Century Hijri",
    description: "The foundational work on Arabic grammar, simply known as 'Al-Kitab' (The Book). Compiled by the Persian scholar Sibyawayh, it established the rules of classical Arabic.",
    coverImage: "https://images.pexels.com/photos/7249185/pexels-photo-7249185.jpeg"
  },
  {
    id: 14,
    title: "Al-Fiqh 'ala al-Madhahib al-Arba'ah",
    arabicTitle: "الفقه على المذاهب الأربعة",
    author: "Abdul Rahman al-Jaziri",
    authorArabic: "عبد الرحمن الجزيري",
    category: "Fiqh",
    subject: "Comparative Jurisprudence",
    madhab: "Comparative",
    language: "Arabic",
    creed: "Ash'ari",
    era: "Modern",
    bookType: "Commentary",
    pages: 2400,
    publicationYear: "1360 AH",
    scholarEra: "14th Century Hijri",
    description: "A comprehensive comparison of Islamic jurisprudence across the four Sunni schools of thought (Hanafi, Maliki, Shafi'i, and Hanbali). An essential reference for comparative fiqh.",
    coverImage: "https://images.pexels.com/photos/16126230/pexels-photo-16126230.jpeg"
  },
  {
    id: 15,
    title: "Fath al-Bari",
    arabicTitle: "فتح الباري",
    author: "Ibn Hajar al-Asqalani",
    authorArabic: "ابن حجر العسقلاني",
    category: "Hadith",
    subject: "Hadith Commentary",
    madhab: "Shafi'i",
    language: "Arabic",
    creed: "Ash'ari",
    era: "Post-Classical",
    bookType: "Commentary",
    pages: 6000,
    publicationYear: "852 AH",
    scholarEra: "9th Century Hijri",
    description: "The most comprehensive and authoritative commentary on Sahih al-Bukhari. Ibn Hajar's masterwork provides detailed explanations, legal rulings, and biographical information.",
    coverImage: "https://images.pexels.com/photos/29808495/pexels-photo-29808495.jpeg"
  },
  {
    id: 16,
    title: "Al-Umm",
    arabicTitle: "الأم",
    author: "Imam al-Shafi'i",
    authorArabic: "الإمام الشافعي",
    category: "Fiqh",
    subject: "Shafi'i Jurisprudence",
    madhab: "Shafi'i",
    language: "Arabic",
    creed: "Athari",
    era: "Salaf",
    bookType: "Matn",
    pages: 3500,
    publicationYear: "204 AH",
    scholarEra: "2nd-3rd Century Hijri",
    description: "The primary jurisprudential work of Imam al-Shafi'i, containing his legal opinions and methodology. It forms the foundation of the Shafi'i school of Islamic law.",
    coverImage: "https://images.pexels.com/photos/3616003/pexels-photo-3616003.jpeg"
  },
  {
    id: 17,
    title: "Tarikh al-Tabari",
    arabicTitle: "تاريخ الطبري",
    author: "Imam al-Tabari",
    authorArabic: "الإمام الطبري",
    category: "History",
    subject: "Islamic History",
    madhab: "Shafi'i",
    language: "Arabic",
    creed: "Athari",
    era: "Salaf",
    bookType: "Matn",
    pages: 5000,
    publicationYear: "310 AH",
    scholarEra: "3rd-4th Century Hijri",
    description: "History of the Prophets and Kings - a comprehensive chronicle of world history from creation to the early Islamic period. One of the most important historical works in Islam.",
    coverImage: "https://images.pexels.com/photos/945030/pexels-photo-945030.jpeg"
  },
  {
    id: 18,
    title: "Al-Qamus al-Muhit",
    arabicTitle: "القاموس المحيط",
    author: "Al-Firuzabadi",
    authorArabic: "الفيروزآبادي",
    category: "Arabic Language",
    subject: "Arabic Lexicon",
    madhab: "Shafi'i",
    language: "Arabic",
    creed: "Ash'ari",
    era: "Post-Classical",
    bookType: "Reference",
    pages: 1800,
    publicationYear: "817 AH",
    scholarEra: "9th Century Hijri",
    description: "One of the most comprehensive Arabic dictionaries, widely used by scholars. It contains detailed definitions and linguistic analysis of Arabic vocabulary.",
    coverImage: "https://images.pexels.com/photos/7249183/pexels-photo-7249183.jpeg"
  },
  {
    id: 19,
    title: "Zad al-Ma'ad",
    arabicTitle: "زاد المعاد",
    author: "Ibn Qayyim al-Jawziyya",
    authorArabic: "ابن قيم الجوزية",
    category: "Seerah",
    subject: "Prophetic Guidance",
    madhab: "Hanbali",
    language: "Arabic",
    creed: "Athari",
    era: "Post-Classical",
    bookType: "Commentary",
    pages: 2200,
    publicationYear: "751 AH",
    scholarEra: "8th Century Hijri",
    description: "Provisions for the Hereafter - a comprehensive guide derived from the Prophet's life, covering spiritual, legal, and practical aspects of Islamic living.",
    coverImage: "https://images.pexels.com/photos/6099938/pexels-photo-6099938.jpeg"
  },
  {
    id: 20,
    title: "Al-Shifa bi Ta'rif Huquq al-Mustafa",
    arabicTitle: "الشفا بتعريف حقوق المصطفى",
    author: "Qadi 'Iyad",
    authorArabic: "القاضي عياض",
    category: "Seerah",
    subject: "Prophetic Excellence",
    madhab: "Maliki",
    language: "Arabic",
    creed: "Ash'ari",
    era: "Classical",
    bookType: "Commentary",
    pages: 1100,
    publicationYear: "544 AH",
    scholarEra: "6th Century Hijri",
    description: "A beautiful exposition on the rights, virtues, and excellence of Prophet Muhammad (peace be upon him). One of the most beloved works on the Prophet's character.",
    coverImage: "https://images.pexels.com/photos/8164515/pexels-photo-8164515.jpeg"
  }
];

export const categories = [
  "All",
  "Tafsir",
  "Hadith",
  "Fiqh",
  "Aqeedah",
  "Seerah",
  "Arabic Language",
  "Usul al-Fiqh",
  "History",
  "Sufism & Spirituality"
];

export const authors = [
  "All",
  "Imam al-Tabari",
  "Imam Bukhari",
  "Imam Muslim",
  "Imam Malik",
  "Imam al-Shafi'i",
  "Ibn Rushd (Averroes)",
  "Ibn Qudamah",
  "Imam al-Ghazali",
  "Ibn Kathir",
  "Ibn Hisham",
  "Imam al-Nawawi",
  "Imam al-Tahawi",
  "Sibyawayh",
  "Abdul Rahman al-Jaziri",
  "Ibn Hajar al-Asqalani",
  "Al-Firuzabadi",
  "Ibn Qayyim al-Jawziyya",
  "Qadi 'Iyad"
];

export const subjects = [
  "All",
  "Quranic Exegesis - Comprehensive",
  "Quranic Exegesis - Hadith-based",
  "Prophetic Traditions - Sahih",
  "Prophetic Traditions & Fiqh",
  "Ethics & Spirituality",
  "Hadith Commentary",
  "Islamic Creed",
  "Hanbali Jurisprudence",
  "Shafi'i Jurisprudence",
  "Maliki Jurisprudence",
  "Comparative Jurisprudence",
  "Principles of Jurisprudence",
  "Prophetic Biography",
  "Prophetic Guidance",
  "Prophetic Excellence",
  "Islamic History",
  "Arabic Grammar",
  "Arabic Lexicon",
  "Islamic Sciences & Inner Dimensions"
];

export const madhabs = [
  "All",
  "Hanafi",
  "Maliki",
  "Shafi'i",
  "Hanbali",
  "Comparative",
  "Independent",
  "N/A"
];

export const languages = [
  "All",
  "Arabic",
  "English",
  "Urdu",
  "Turkish",
  "Persian",
  "Malay"
];

export const creeds = [
  "All",
  "Athari",
  "Ash'ari",
  "Maturidi",
  "N/A"
];

export const eras = [
  "All",
  "Salaf",
  "Khalaf",
  "Classical",
  "Post-Classical",
  "Modern"
];

export const bookTypes = [
  "All",
  "Matn",
  "Commentary",
  "Translation",
  "Epistle",
  "Compilation",
  "Reference"
];